"""Refuse hand-edits to the files the tools/ pipeline owns.

CLAUDE.md says these are generated and must never be hand-edited. Until now the
only thing enforcing that was ``test_generators_are_idempotent``, which fails
*after* the bad edit is already on disk and usually long after the reasoning
that produced it has scrolled away. This turns the rule into a refusal at the
moment of the write, and names the input file to edit instead.

``translations/*.json`` are only half generated -- the ``entity`` block comes
from the pipeline, the ``config``/``options`` flow strings are hand-maintained
-- so those get a warning rather than a refusal.
"""

from __future__ import annotations

import sys

sys.path.insert(0, str(__import__("pathlib").Path(__file__).resolve().parent))

from _common import allow, emit, payload, repo_relative, touched_path  # noqa: E402

_PKG = "custom_components/bavariandata"

# path -> what to edit instead
GENERATED = {
    f"{_PKG}/catalogue.json": (
        "tools/curated_titles.json (then re-run tools/build_catalogue.py)"
    ),
    f"{_PKG}/descriptor_metadata.py": (
        "tools/curated_titles.json (then re-run tools/generate_metadata.py)"
    ),
    "docs/reference/telematics-fields.md": (
        "tools/curated_titles.json (then re-run tools/generate_reference_doc.py)"
    ),
}

PARTLY_GENERATED = {
    f"{_PKG}/translations/en.json",
    f"{_PKG}/translations/de.json",
}


def main() -> None:
    data = payload()
    path = touched_path(data)
    if path is None:
        allow()

    rel = repo_relative(path)
    if rel is None:
        allow()

    if rel in GENERATED:
        emit(
            {
                "hookSpecificOutput": {
                    "hookEventName": "PreToolUse",
                    "permissionDecision": "deny",
                    "permissionDecisionReason": (
                        f"{rel} is generated by the tools/ pipeline and must not be "
                        f"hand-edited. Edit {GENERATED[rel]}, then re-run steps 1-4 "
                        "from tools/README.md and `pytest tests/test_catalogue.py`."
                    ),
                }
            }
        )

    if rel in PARTLY_GENERATED:
        emit(
            {
                "systemMessage": (
                    f"{rel}: the `entity` block is generated -- edit "
                    "tools/curated_titles.json and re-run the pipeline instead. "
                    "Only `config`/`options` are hand-maintained here, and a change "
                    "to one language needs the same change in the other."
                )
            }
        )

    allow()


if __name__ == "__main__":
    main()
